# Generated by Django 4.0 on 2021-12-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fechCrea', models.DateTimeField(auto_now_add=True)),
                ('usrModif', models.IntegerField(blank=True, null=True)),
                ('fechModif', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(help_text='Descripción de la categoría', max_length=100, unique=True)),
                ('usrCrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
