# Generated by Django 4.0 on 2021-12-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='fecha_facura',
            new_name='fecha_factura',
        ),
        migrations.RenameField(
            model_name='comprasenc',
            old_name='observaciones',
            new_name='observacion',
        ),
    ]
